# Generated by Django 4.1.2 on 2022-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.IntegerField(null=True)),
                ('nomeFantasia', models.CharField(max_length=255, null=True)),
                ('idVeiculo', models.IntegerField(null=True)),
                ('veiculoNome', models.CharField(max_length=255, null=True)),
                ('idLinha', models.IntegerField(null=True)),
                ('linhaNome', models.CharField(max_length=255, null=True)),
                ('idMotorista', models.IntegerField(null=True)),
                ('motoristaNome', models.CharField(max_length=255, null=True)),
                ('motoristaMatricula', models.IntegerField(null=True)),
                ('idViagem', models.IntegerField(null=True)),
                ('viagemInicio', models.DateTimeField(null=True)),
                ('viagemRetorno', models.DateTimeField(null=True)),
                ('viagemFim', models.DateTimeField(null=True)),
                ('viagemMetrosPercorridos', models.FloatField(null=True)),
                ('dataHoraGPS', models.DateTimeField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('hodometro', models.FloatField(null=True)),
                ('inercia', models.FloatField(null=True)),
                ('rpmElevado', models.FloatField(null=True)),
            ],
        ),
    ]
